nginx:
    prog: "/usr/bin/ls"
    args:
        - "-l"
        - "-a"
        - "/"
        - "dsassdd"
        - "vxc,vnn"
    numprocs: 1
    umask: 022
    workingdir: /home/user
    autostart: true
    autorestart: unexpected
    exitcodes:
        - 0
        - 2
    startretries: 3
    starttime: 5
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/ls.out
    stderr: /tmp/ls.err
    env:
        STARTED_BY: taskmaster
        ANSWER: 42
